import type { Metadata } from "next";
import "./styles/globals.css";
import '@uigovpe/styles';
import { Inter } from 'next/font/google';
import { LayoutProvider, UiProvider } from "@uigovpe/components";
import { PageProvider } from "./infrastructure/context/PageContext";

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Portal de Compras Públicas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <PageProvider>
          <LayoutProvider>
            <UiProvider>
              {children}
            </UiProvider>
          </LayoutProvider>
        </PageProvider>
      </body>
    </html>
  );
}
